name: okta_flutter
description: Okta Flutter package makes it easy to add authentication to flutter apps. This library is a wrapper around Okta OIDC Android and Okta OIDC iOS.
version: 0.0.4
homepage: https://github.com/Mobioxy/okta_flutter_package
documentation: https://github.com/Mobioxy/okta_flutter_package

environment:
  sdk: ">=2.15.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mobioxy.okta_flutter
        pluginClass: OktaFlutterPlugin
      ios:
        pluginClass: OktaFlutterPlugin
